config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'splashes#index'

  resources :categories, only: %i[index show new create] do
    resources :records, only: %i[index show new create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Category, user: user
    can :manage, Record, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_record.rb
class CategoriesRecord < ApplicationRecord
  belongs_to :category
  belongs_to :record
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :categories_records
  has_many :records, through: :categories_records
  has_one_attached :icon

  validates :name, presence: true, length: { maximum: 100 }
  validates :icon, presence: true, length: { maximum: 250 }

  def most_recent
    records.order(created_at: :DESC)
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :categories_records
  has_many :categories, through: :categories_records

  validates :name, presence: true, length: { maximum: 100 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :records

  validates :name, presence: true, length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || categories_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.includes(:records)
  end

  def show; end

  def new; end

  def create
    category_name = category_params['name'].downcase
    category = current_user.categories.new(name: category_name, icon: category_params['icon'])
    if Category.where(name: category_name).exists?
      redirect_to new_category_url, notice: 'This category name already exists'
      nil
    elsif category.save
      flash[:success] = 'You successfully added a category to your application'
      redirect_to categories_url
    else
      flash.now[:error] = 'Error: You could not create a new category'
      render :new
    end
  end

  private

  def category_params
    params.require(:add_category).permit(:name, :icon)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @category = current_category
  end

  def new
    @category = current_category
  end

  def create
    record_name = record_params['name']
    record_amount = record_params['amount']
    category_ids = record_params['category_ids'].slice(1..-1)
    category = current_category
    @record = current_user.records.new(name: record_name, amount: record_amount)
    if @record.save
      category_ids.each do |id|
        @record.categories_records.create!(category_id: id.to_i)
      end
      flash[:success] = 'You completed this transaction successfully'
      redirect_to category_records_path(category)
    else
      flash.now[:error] = 'New transaction could not be created.'
      render :new
    end
  end

  def current_category
    @category = current_user.categories.includes(:records).find(params[:category_id])
  end

  private

  def record_params
    params.require(:add_record).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/views/categories/index.html.erb
<div>
    <%= render partial: "shared/navbar", locals: { variable: 'CATEGORIES', path: root_path } %>
  </div>
  <main class="categories-cont">
  <div class="d-flex d-flex-column user-div">
    <h1 class="splash-header"><%= current_user.name %></h1>
    <div class="d-flex gift-div">
      <span>Gift Credit</span>
      <span class="dollar-amount">$145</span>
    </div>
  </div>
  <% @categories.each do |category| %>
    <%= link_to category_records_path(category) do %>
      <article class="transaction-details-div d-flex">
        <div class="icon-placeholder">
          <%= image_tag(category.icon) %>
        </div>
        <div class="info-div d-flex d-flex-column space-between">
          <div class="d-flex space-between">
            <span><%= category.name %></span>
            <span class="dollar-amount">
              $<%= category.records.reduce(0) { |sum, item| sum + item.amount } %>
            </span>
          </div>
          <div class="date"><%= category.created_at.strftime('%d %b %Y') %></div>
        </div>
      </article>
    <% end %>
  <% end %>
  <div class="new-btn-div">
    <%= button_to 'Add New Category', new_category_url, method: :get %>
  </div>
</main>

app/views/categories/new.html.erb
<main class="new-categories-cont">
  <div>
    <%= render partial: "shared/navbar", locals: { variable: 'NEW CATEGORY', path: categories_path } %>
  </div>
  <h1 class="register-header">Register Your Category</h1>
  <%= form_with url: categories_path, method: :post, local: true, scope: :add_category do |form| %>

      <div>
        <%= form.text_field :name,placeholder: :name, class: 'form-field', :required => true %>
      </div>

      <div>
      <%= form.label :icon, class: 'file-upload-label' do %>
        <p class="upload-image">Upload Image</p>
        <span class="file-name">No File Chosen</span>
      <% end %><br>
      <%= form.file_field :icon, class: 'form-field', :required => true %>
      </div>

      <div class="new-btn-div">
      <%= form.submit 'Register Category', class: 'submit-btn reg-cat' %>
    </div>
    <% end %>
</main>
<script>
  const FILEUPLOADER = document.querySelector('#add_category_icon');
  FILEUPLOADER.addEventListener("change", (e) => {
    document.querySelector('.file-upload-label > span').style.display = 'block';
    document.querySelector('.file-upload-label > span').innerText = e.target.files[0].name;
    document.querySelector('.file-upload-label > span').style.color = '#5fb523';
    document.querySelector('.file-upload-label > p').style.backgroundColor = "#5fb523";
    document.querySelector('.file-upload-label > p').innerText = "Uploaded ✓"
  })

  document.querySelector('.reg-cat').addEventListener('click', () => {
    if ((document.querySelector('.file-upload-label > span').innerText == 'No File Chosen') && 
    (document.querySelector('#add_category_name').value !== '')) {
      alert('select an icon for this category!')
    }
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Italianno&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Italiana&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/29d7bf5b00.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/9ef5f4f831.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/index.html.erb
<div>
  <%= render partial: "shared/navbar", locals: { variable: 'TRANSACTIONS', path: categories_path } %>
</div>
<main class="records-cont">
  <div class="top-part">
    <div class="icon-placeholder d-flex space-between record-img-div">
      <%= image_tag(@category.icon) %>
      <h1><%= @category.name %></h1>
    </div>
    <div class="payment-div d-flex space-between">
      <p class="dollar-amount">Total Payment:</p>
      <p class="dollar-amount">$<%= @category.records.reduce(0) { |sum, item| sum + item.amount }%> </p>
    </div>
  </div>
  <div class="transaction-general-div">
    <% @category.most_recent.each do |record| %>
      <p class="id-number">Transaction No <%= record.id %> </p>
      <div class="transaction-detail d-flex space-between">
        <p> <%= record.name %> </p>
        <p>$<%= record.amount %></p>
      </div>
      <p class="date"> <%= record.created_at.strftime("%d %b %Y at %I:%M%p") %> </p>
    <% end %>
  </div>
  <div class="new-btn-div">
    <%= button_to 'Add New Transaction', new_category_record_url(@category), method: :get %>
  </div>
</main>

app/views/records/new.html.erb
<main class="new-record-cont">
  <div>
    <%= render partial: "shared/navbar", locals: { variable: 'NEW TRANSACTION', path: category_records_path(@category) } %>
  </div>
  <h1 class="register-header">Create Your Transaction</h1>
    <%= form_with url:  category_records_path(@category), method: :post, local: true, scope: :add_record do |form| %>

      <div>
        <%= form.text_field :name, placeholder: :name, class: 'form-field', :required => true %>
      </div>

      <div>
        <%= form.number_field :amount, placeholder: :amount, class: 'form-field', step: 0.5, :required => true %>
      </div>

      <div class="general-checkbox-div">
        <%= form.label :categories, 'Select Category/Categories', class: 'checkbox-main-label' %><br>
        <%= form.collection_check_boxes :category_ids, Category.all, :id, :name, class: 'collection' do |c| %>
          <div class="checkbox-div">
            <%= c.check_box %>
            <%= c.label class: 'checkbox-label' %><br>
          </div>
        <% end %>
      </div>
      <div class="new-btn-div">
        <%= form.submit 'Create Transaction' %>
      </div>
    <% end %>
</main>

app/views/shared/_navbar.html.erb
<nav class="navi-bar-cont d-flex">
  <div>
  <%= link_to root_path, class: 'back-link' do %>
    <i class="fa-solid fa-circle-left"></i>
  <% end %>
  </div>
  <div> <%= variable %> </div>
  <div>
    <%= button_to destroy_user_session_url, method: :delete, class: 'sign-out-btn' do %>
      <i class="fas fa-right-from-bracket"></i>
    <% end %>
  </div>
</nav>
<div class="flash-cont d-flex">
  <% flash.each do |name, msg| -%>
    <%= content_tag :span, msg, class: name %>
  <% end -%>
</div>

app/views/splashes/index.html.erb
<main class="splash-page-cont">
  <h1 class="splash-header">Welcome</h1>
  <h2 class="appli-name">Transactions App</h2>
  <div>
    <%= button_to 'LOG IN', new_user_session_path, method: :get, class: 'devise-btn' %>
    <%= button_to 'SIGN UP', new_user_registration_path, method: :get, class: 'devise-btn log-in-btn' %>
  </div>
</main>